# Generated by Django 3.2.20 on 2023-08-05 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenseapp', '0003_expense'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Expense',
        ),
    ]
