# Generated by Django 3.2.18 on 2023-04-15 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenseapp', '0004_expenses_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expenses',
            name='user',
        ),
    ]
